# Generated by Django 5.2.5 on 2025-08-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('escolaridade', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Técnico'), ('superior', 'Ensino Superior'), ('pos', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=20, verbose_name='Escolaridade')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('outro', 'Outro')], max_length=20, verbose_name='Estado Civil')),
                ('cargo', models.CharField(max_length=100)),
                ('funcao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Função')),
                ('local_trabalho', models.CharField(max_length=100)),
                ('tempo_unicoop', models.CharField(max_length=50, verbose_name='Tempo na Unicoop')),
                ('tempo_funcao', models.CharField(max_length=50, verbose_name='Tempo na função atual')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('resposta1', models.TextField(verbose_name='Situações de estresse ou insegurança')),
                ('resposta2', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Sinais de sobrecarga ou assédio')),
                ('resposta2_descricao', models.TextField(verbose_name='Descrição se respondeu Sim')),
                ('resposta3', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Como a liderança lida com saúde mental?')),
                ('resposta3_descricao', models.TextField(verbose_name='Descrição se respondeu Sim')),
                ('resposta4', models.CharField(choices=[('Positivamente', 'Positivamente'), ('Negativamente', 'Negativamente')], max_length=50, verbose_name='Impacto do ambiente no trabalho')),
                ('resposta4_descricao', models.TextField(verbose_name='Descrição do impacto')),
                ('resposta5', models.TextField(verbose_name='Sugestões de melhorias')),
                ('resposta6', models.TextField(verbose_name='Comentários adicionais')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
